import { Deck } from "./types";

export const SAMPLE_DAIK_TOPIC = "Agentic AI";

export const SAMPLE_DECK: Deck = {
  title: "Agentic AI",
  subtitle: "From Prompts to Autonomous Agents",
  author: "OpenSpark AI",
  topic: SAMPLE_DAIK_TOPIC,
  slides: [
    {
      slideNumber: 1,
      title: "Agentic AI",
      subtitle: "The Next Frontier in Artificial Intelligence",
      layoutType: "title",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#0f172a",
        text: "#f8fafc",
      },
      visualMetaphor: "Dark gradient with floating neural network nodes",
      blocks: [
        { type: "heading", content: "Agentic AI" },
        { type: "body", content: "From Prompts to Autonomous Agents" },
      ],
    },
    {
      slideNumber: 2,
      title: "What is Agentic AI?",
      layoutType: "split",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#ffffff",
        text: "#1e293b",
      },
      visualMetaphor: "Side-by-side comparison of traditional vs agentic AI",
      blocks: [
        { type: "heading", content: "What is Agentic AI?" },
        { type: "body", content: "AI systems that plan, reason, and act autonomously." },
        { type: "callout", content: "Unlike chatbots, agents can use tools and take actions." },
      ],
    },
    {
      slideNumber: 3,
      title: "Key Capabilities",
      layoutType: "grid",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#f8fafc",
        text: "#1e293b",
      },
      visualMetaphor: "Grid of capability cards with icons",
      blocks: [
        { type: "heading", content: "Core Capabilities" },
        { type: "bullet", content: "Reasoning & Planning" },
        { type: "bullet", content: "Tool Use" },
        { type: "bullet", content: "Memory & Context" },
        { type: "bullet", content: "Multi-step Tasks" },
      ],
    },
    {
      slideNumber: 4,
      title: "Agent Architecture",
      layoutType: "body",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#ffffff",
        text: "#1e293b",
      },
      visualMetaphor: "Flowchart showing perception, reasoning, action loop",
      blocks: [
        { type: "heading", content: "Agent Architecture" },
        { type: "body", content: "Observe" },
        { type: "body", content: "Think" },
        { type: "body", content: "Act" },
      ],
    },
    {
      slideNumber: 5,
      title: "Use Cases",
      layoutType: "comparison",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#f1f5f9",
        text: "#1e293b",
      },
      visualMetaphor: "Split comparison of business vs personal use cases",
      blocks: [
        { type: "heading", content: "Enterprise" },
        { type: "bullet", content: "Customer Support" },
        { type: "bullet", content: "Data Analysis" },
        { type: "heading", content: "Personal" },
        { type: "bullet", content: "Task Automation" },
        { type: "bullet", content: "Learning Assistant" },
      ],
    },
    {
      slideNumber: 6,
      title: "Market Impact",
      layoutType: "data-viz",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#ffffff",
        text: "#1e293b",
      },
      visualMetaphor: "Bar chart showing AI market growth",
      blocks: [
        { type: "heading", content: "$500B+ by 2030" },
        { type: "body", content: "Agentic AI market projected growth" },
        { type: "callout", content: "60% of enterprises adopting by 2027" },
      ],
    },
    {
      slideNumber: 7,
      title: "Ethical Considerations",
      layoutType: "quote",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#0f172a",
        text: "#f8fafc",
      },
      visualMetaphor: "Dark themed quote slide with balance scale icon",
      blocks: [
        { type: "heading", content: "With great power comes great responsibility." },
        { type: "body", content: "Key concerns: Bias, Transparency, Control, Privacy" },
      ],
    },
    {
      slideNumber: 8,
      title: "The Future",
      layoutType: "image-focused",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#ffffff",
        text: "#1e293b",
      },
      visualMetaphor: "Futuristic timeline showing AI evolution",
      blocks: [
        { type: "heading", content: "2026: Multi-agent systems" },
        { type: "heading", content: "2028: Self-improving agents" },
        { type: "heading", content: "2030: Artificial General Intelligence" },
      ],
    },
    {
      slideNumber: 9,
      title: "Getting Started",
      layoutType: "split",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#f8fafc",
        text: "#1e293b",
      },
      visualMetaphor: "Split layout with tools on left, steps on right",
      blocks: [
        { type: "heading", content: "Tools" },
        { type: "bullet", content: "LangChain" },
        { type: "bullet", content: "CrewAI" },
        { type: "heading", content: "Steps" },
        { type: "bullet", content: "Define Goal" },
        { type: "bullet", content: "Choose Tools" },
      ],
    },
    {
      slideNumber: 10,
      title: "Thank You",
      layoutType: "title",
      colorPalette: {
        primary: "#3b82f6",
        secondary: "#1e40af",
        accent: "#d946ef",
        background: "#0f172a",
        text: "#f8fafc",
      },
      visualMetaphor: "Dark gradient with thank you message and QR code placeholder",
      blocks: [
        { type: "heading", content: "Thank You!" },
        { type: "body", content: "Questions?" },
      ],
    },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  version: 1,
};
